from pathlib import Path

DEFAULT_INPUT_DIR: Path = Path("import")
DEFAULT_OUTPUT_DIR: Path = Path("export")
SAM_MODEL_ID: str = "facebook/sam-vit-base"
SAM_CONFIDENCE_THRESHOLD: float = 0.75
HOUGH_THRESHOLD: int = 100
HOUGH_MIN_LINE_LENGTH_RATIO: float = 0.5
HOUGH_MAX_LINE_GAP: int = 20
HOUGH_ANGLE_TOLERANCE_PX: int = 5
SEPARATOR_MIN_HEIGHT_RATIO: float = 0.70
TITLE_BLOCK_ZONE_LEFT_RATIO: float = 0.70
TITLE_BLOCK_ZONE_RIGHT_RATIO: float = 0.95
BORDER_OPEN_KERNEL_SIZE: int = 4
BORDER_MIN_HEIGHT_RATIO: float = 0.50
BORDER_MIN_WIDTH_RATIO: float = 0.40
BORDER_APPROX_POLY_EPSILON: float = 0.02
